# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e99f1a5c7bccbba2c58794e9d6128d2c00892e22af0ace9140266373442d231d4aa37c2e660f3b2e412ed50c9236c8752ff6d6939b0557be5ac27710b520aee7

test:
  secret_key_base: 370f512cfdf1e285eb0701493cc27924138e0742b9e4549cd5be49609da200c502e4d21e1242a3fe784cacf2c1d9d6502db226d9679744a851ed1fe602c86065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
